name: fitness_app_hello_world
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  smooth_page_indicator: ^1.2.0+3
  animated_weight_picker: ^1.0.3
  firebase_messaging: ^15.1.0
  cloud_firestore: ^5.3.0
  http: ^1.2.2
  firebase_auth: ^5.2.0
  fluttertoast: ^8.2.12
  google_generative_ai: ^0.4.5
  flutter_markdown: ^0.7.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
