// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZAua5JwDtZ8YCVzlfRrGAyVRP9mNypI',
    appId: '1:976150274309:web:92edca0b1af6bafc6a176c',
    messagingSenderId: '976150274309',
    projectId: 'hello-world-fitness-app',
    authDomain: 'hello-world-fitness-app.firebaseapp.com',
    storageBucket: 'hello-world-fitness-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1wd0uTuAde668SH6DO_e0BFMJ1DML_lI',
    appId: '1:976150274309:android:c5640091a3250d8d6a176c',
    messagingSenderId: '976150274309',
    projectId: 'hello-world-fitness-app',
    storageBucket: 'hello-world-fitness-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEMXDm9KNwTzOvRrnGEsqlQRUgl5o92bU',
    appId: '1:976150274309:ios:3bbed6fcdcb05e496a176c',
    messagingSenderId: '976150274309',
    projectId: 'hello-world-fitness-app',
    storageBucket: 'hello-world-fitness-app.appspot.com',
    iosBundleId: 'com.example.fitnessAppHelloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEMXDm9KNwTzOvRrnGEsqlQRUgl5o92bU',
    appId: '1:976150274309:ios:3bbed6fcdcb05e496a176c',
    messagingSenderId: '976150274309',
    projectId: 'hello-world-fitness-app',
    storageBucket: 'hello-world-fitness-app.appspot.com',
    iosBundleId: 'com.example.fitnessAppHelloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClZAua5JwDtZ8YCVzlfRrGAyVRP9mNypI',
    appId: '1:976150274309:web:58c8b79dd4cd2a476a176c',
    messagingSenderId: '976150274309',
    projectId: 'hello-world-fitness-app',
    authDomain: 'hello-world-fitness-app.firebaseapp.com',
    storageBucket: 'hello-world-fitness-app.appspot.com',
  );
}
